# Generated by Django 4.0.5 on 2022-07-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeluqueria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='persona_atendida',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
