# Generated by Django 4.0.5 on 2022-07-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeluqueria', '0003_rename_alisados_tratamientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientos',
            name='descripcion',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='unias',
            name='descripcion',
            field=models.CharField(max_length=4000),
        ),
    ]
