# Generated by Django 4.0.5 on 2022-07-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeluqueria', '0004_alter_tratamientos_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.IntegerField()),
                ('Consulta', models.CharField(max_length=40000)),
            ],
        ),
    ]
