# Generated by Django 4.0.5 on 2022-07-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeluqueria', '0008_alter_experiencia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tratamientos'),
        ),
    ]
